### PR TITLE
Specify swift version generically

### PR DESCRIPTION
**Pull request by frederoni**
As of version 1.1.0.rc.2, Cocoapods extracts swift version from the `.swift-version` file.

### CODE REVIEW

**Comment by 1ec5** [comment]
Any idea why Bitrise bots are failing?

**Comment by superpeteblaze** [comment]
@1ec5 Not sure. Tried to check the build logs but not authorized on bitrise.

**Comment by 1ec5** [comment]
Sorry, I forgot to post an update here. We figured out the issue over in mapbox/MapboxGeocoder.swift#74, and I fixed it in mapbox/MapboxGeocoder.swift#57 by merging in master, which had mapbox/MapboxGeocoder.swift@3f6b60e16c5ce36fd054ae3eb556f91e186afa2d. I just upgraded the build bots to the Xcode 8 stack. If you pull in mapbox/MapboxDirections.swift#70, the CocoaPods step will use CocoaPods 1.1.rc.2 instead of the ancient 0.38 and everything will (hopefully) pass. I’ve added you to the four MapboxDirections applications on Bitrise so you can see the build results.

**Comment by superpeteblaze** [comment]
Thanks @1ec5, I'll have a look

**Pull request merged**
