### PR TITLE
Removed SwiftyJSON dependency. Simplified JSON logic.

### PR DESCRIPTION
**Pull request by harlanhaskins**
The SwiftyJSON dependency wasn't really necessary. This'll allow us to make a nice CocoaPod much easier.

### CODE REVIEW

**Comment by incanus** [comment]
Thanks for kicking this off @harlanhaskins. There's a lot going on in here aside from SwiftyJSON, though (`Release` build, whitespace, checkout-related things). Can you clean it up a bit so we can evaluate in context, and more importantly, possibly merge _just_ the JSON improvements?

**Comment by harlanhaskins** [comment]
Apologies for the whitespace; I ran `ctrl+i`.

I'm not quite sure why Xcode added that `defaultConfigurationName` thing -- I think that's something Xcode 6 does automatically.

**Comment by harlanhaskins** [comment]
Also, I accidentally committed my Xcode workspace data because the project had no gitignore.
I can remove the gitignore, but I'd say it's a very useful thing to have.

**Comment by harlanhaskins** [comment]
Also, the checkout file needed to be modified if SwiftyJSON is no longer going to be a hard dependency.

**Comment by incanus** [comment]
Closing in favor of review of #7.

**Pull request closed without merging**
